#!/usr/bin/env bash

chmod 666 /dev/input/*
chmod -R 777 /dev/dri/*

if [ ! $(getent group ${PGID}) ]; then
	groupadd -g ${PGID} abc
fi

useradd -m -d /home/abc -p /bin/bash -g root -G sudo,audio,video,plugdev -u ${PUID} abc

mkdir -p /home/abc/{.local,.config}
ln -s /config /home/abc/.config/PCSX2
ln -sf /memcards /home/abc/.config/PCSX2/memcards
ln -sf /bios /home/abc/.config/PCSX2/bios

chown -R abc.${PGID} /home/abc

# libGSdx-AVX2.so will crash PCSX2 on non-AVX2 CPUs.
if [ ! $(grep "avx" /proc/cpuinfo) ]; then
	rm /usr/lib/games/PCSX2/libGSdx-AVX2.so
fi

cd /images
echo MESA_LOADER_DRIVER_OVERRIDE $MESA_LOADER_DRIVER_OVERRIDE
sudo -H -E -g $(getent group ${PGID} | cut -d: -f 1) -u abc PCSX2 "$@"
