#!/usr/bin/env bash

FILENAME=$(readlink -f "$1")

IMGDIR=$(dirname "${FILENAME}")
IMG=/images/$(basename "${FILENAME}")

echo imgdir ${IMGDIR} img ${IMG}

	#-v /etc/machine-id:/etc/machine-id:ro \

docker run -it --rm \
  --net host \
  --cap-add NET_ADMIN \
	--device /dev/input \
  --device /dev/bus/usb \
  --device /dev/dri \
  -v /dev/dri/by-path:/dev/dri/by-path \
	-v /run/udev/data:/run/udev/data \
  -e PUID=$(id -u) \
  -e PGID=$(id -g) \
  -e DISPLAY=unix$DISPLAY \
  -e PULSE_SERVER=unix:/tmp/.pulse-native \
  -v /run/user/$(id -u)/pulse/native:/tmp/.pulse-native	\
  -v /tmp/.X11-unix/X0:/tmp/.X11-unix/X0 \
  -v /etc/localtime:/etc/localtime:ro \
  -v ${PWD}/data/bios:/bios \
  -v ${IMGDIR}:/images \
  -v ${PWD}/config:/config \
  pcsx2 \
	/app/bootstrap "${IMG}"
  #PCSX2 "${IMG}"

# vim: ts=2 sw=2 et:
